### ISSUE TITLE
Menu and tool tip background colour

### ISSUE THREAD

**Issue by helambuapps** [flexiondotorg/ubuntu-mate-themes#44] opened 2016-10-28 21:21 UTC
## SciLab 5.5.2 in the Ambient-MATE theme

![image](https://cloud.githubusercontent.com/assets/7665028/19821893/80457bf0-9dac-11e6-98c9-b0e4c4e0c388.png)
_Looks bad on some themes_
## SciLab 5.5.2 in the TraditionalOk theme:

![image](https://cloud.githubusercontent.com/assets/7665028/19822236/2fa65f00-9dae-11e6-870b-f7e83434480d.png)
_Looks all right on some themes_
## Tool tip background colour

No matter what theme I use:
The tool tip background colour for certain applications is not right as well. For example, Quartus II IDE, Formulator (MathML Equation Editor) etc.
This is how it looks:
![image](https://cloud.githubusercontent.com/assets/7665028/19822578/e7e23688-9daf-11e6-8183-ca0a1470c226.png)
_Looks bad on all themes_

**Comment by raveit65** [comment] 2016-10-29 11:52
Are those gtk3 applications?
Looks like gtk2.....
And please give me links to project names, i'm using fedora and i'm not familiar how they called in ubuntu.

**Comment by helambuapps** [comment] 2016-10-29 12:57
Not sure if the first one is using GTK3 for UIs.

The GUI for Scilab is written in Java, maybe it is using Swing but I am not sure.
sudo apt-get install scilab
similar in fedora
http://www.scilab.org/scilab/about

The GUI for Quartus 2 IDE is written in an old version of Qt (version 4 or even 3). I mean an old school widget based Qt not a modern QtQuick/QML. Formulator has a similar issue. Maybe it is written in an old version of Qt as well but I am not sure.

Please note, Quartus 2 is a really big piece of software. About 8 GB download.
https://www.altera.com/downloads/download-center.html

Formulator is tiny little. The toolbar makes it look like the UI is based on Qt widgets.
sudp apt-get install formulator
similar in fedora
http://www.mmlsoft.com/index.php/downloads

**Comment by raveit65** [comment] 2016-10-30 05:58
Ok, scilab is java based. I don't know how java apps are working with gtk+ themes.
What i see is that scilab ignore the fg color from menuentries if the bg color is different from main bg color in other themes too. Same with BlackMate a dark theme, but here the fg color isn't different from main fg colors.

OT applications are well known that they won't work well with gtk+ themes.

**Comment by flexiondotorg** [comment] 2017-03-28 16:54
I'm sorry the application you've mentioned are all Java based and the issues you've identified can't be fixed in the themes. The root cause of the Java GTK translation not being very robust.

**Closed by flexiondotorg** 2017-03-28 16:54 UTC
